name: ''
description: 根目录，按照内容与来源分类
curator: ''
source: ''
tags: []
license: ''
files:
- name: independence_repo
  filename: independence_repo.json
  type: other
  format: Unknown Format
  size: 2
  md5: d751713988987e9331980363e24189ce
  page: independence_repo.json
subdirs:
- 交换
- 催眠
- 其他
- 变性
- 变装
- 变身
- 改造
- 皮物
- 资源
- 附身
